Repository LingoBell/LingoBell-FrontEnd, pull requests merged in 2024-08, with the labels that each got.

#39 api restful 정리
  src/apis/ChatAPI.js
  src/apis/PartnerAPI.js
  src/apis/UserAPI.js
  src/components/atomic/pages/ProfileList.js
Labels: 😸API

#42 Show Chat history
  src/components/atomic/pages/LiveChat.js
  src/components/atomic/pages/Video.js
Labels: 💻Feature

#46 Ft/video
  src/apis/ChatAPI.js
  src/components/atomic/pages/LiveChat.js
  src/components/atomic/pages/Video.js
  webpack.config.js
Labels: 🌀BugFix, 💻Feature

#45 Complete edit my page feature
  src/apis/UserAPI.js
  src/components/atomic/pages/ProfilePage.js
Labels: 💻Feature

#52 video에 facelandmark 추가
  package-lock.json
  package.json
  src/components/atomic/pages/UseFaceMask.js
  src/components/atomic/pages/Video.js
Labels: 💻Feature

#57 Jay/whisperstreaming
  src/components/atomic/molecules/ChatForm.js
  src/components/atomic/pages/LiveChat.js
Labels: 💻Feature

#62 Jay/whisperstreaming
  src/components/atomic/molecules/ChatForm.js
  src/components/atomic/pages/LiveChat.js
  src/components/atomic/pages/Video.js
  src/redux/userSlice.js
Labels: 😸API, 💻Feature, AI

#63 영상통화 에러 해결
  src/apis/ChatAPI.js
  src/components/atomic/pages/LiveChat.js
  src/components/atomic/pages/Video.js
  webpack.config.js
Labels: 🌀BugFix

#66 facemask select 기능 추가
  src/assets/images/action.jpg
  src/assets/images/bono.png
  src/assets/images/ddung.png
  src/assets/images/gak.png
  src/assets/images/jocker.jpg
  src/components/atomic/pages/LiveChat.js
  src/components/atomic/pages/Video.js
  webpack.config.js
Labels: 😸API, 🌀BugFix, 💻Feature

#65 Jay/whisperstreaming
  package-lock.json
  package.json
  src/apis/ChatAPI.js
  src/components/atomic/organisms/ChatHistoryDetail.js
  src/components/atomic/pages/LiveChat.js
  src/components/atomic/pages/Video.js
  src/redux/userSlice.js
Labels: 😸API, 🌀BugFix, 💻Feature, AI

#71 mask 상대방에게 적용
  src/components/atomic/pages/Video.js
Labels: 😸API, 🌀BugFix, 💻Feature

#77 video image frame 전송
  src/components/atomic/pages/Video.js
  webpack.config.js
Labels: 😸API, 💻Feature, AI

#78 stt 기능 추가
  public/realtime-audio-processor.js
  src/App.js
  src/components/atomic/pages/LiveChat.js
  src/components/atomic/pages/STT.js
  src/components/atomic/pages/Video.js
Labels: 😸API, 💻Feature, AI

#79 stt + translation 기능 구현 완료
  src/components/atomic/pages/LiveChat.js
  src/components/atomic/pages/STT.js
Labels: 😸API, 💻Feature, AI

#83 stt partner socket 통신 추가
  src/components/atomic/pages/LiveChat.js
  src/components/atomic/pages/STT.js
  src/components/atomic/pages/Video.js
Labels: 😸API, 🌀BugFix, 💻Feature, 🥝Refactor, AI

#84 STT auto-connection
  src/App.js
  src/components/atomic/pages/LiveChat.js
  src/components/atomic/pages/Video.js
Labels: 💻Feature

#86 auto recording 기능 추가
  src/components/atomic/pages/LiveChat.js
  src/components/atomic/pages/Video.js
  webpack.config.js
Labels: 🌀BugFix, 🥝Refactor, AI
