Repository LingoBell/LingoBell-FrontEnd, pull requests merged in 2024-07, with the labels that each got.

#18 Modal component
  src/App.js
  src/components/atomic/molecules/Modal.js
  src/components/atomic/pages/ChatHistory.js
  src/components/atomic/pages/Main.js
Labels: 💻Feature, ✨Style

#20 ChatMessage 리팩토링
  src/App.js
  src/components/atomic/atoms/ChatMessage.js
  src/components/atomic/atoms/Color.js
  src/components/atomic/molecules/ChatForm.js
Labels: 🥝Refactor, ✨Style

#21 Modal component
  src/components/atomic/molecules/Modal.js
  src/components/atomic/molecules/ProfileItem.js
  src/components/atomic/pages/ChatHistory.js
Labels: 💻Feature, ✨Style

#22 Create modal contents for Chat
  src/components/atomic/molecules/Modal.js
  src/components/atomic/pages/ChatHistory.js
Labels: 💻Feature

#24 Jay/modal
  src/components/atomic/pages/ChatHistory.js
Labels: 💻Feature

#26 Show profile info on modal
  src/components/atomic/molecules/Modal.js
  src/components/atomic/pages/ChatHistory.js
Labels: 💻Feature

#31 create chatting room
  src/App.js
  src/apis/ChatAPI.js
  src/apis/UserAPI.js
  src/components/atomic/molecules/Modal.js
  src/components/atomic/molecules/ProfileItem.js
  src/components/atomic/pages/LiveChat.js
  src/components/atomic/pages/ProfileList.js
  src/components/atomic/pages/Video.js
  src/consts/sampleData.js
  src/redux/userSlice.js
Labels: 😸API, 💻Feature

#33 채팅 요청한 유저 목록 api 수정
  src/App.js
  src/apis/ChatAPI.js
  src/components/atomic/pages/ProfileList.js
  src/components/atomic/pages/Video.js
Labels: 😸API, 🌀BugFix, 💻Feature

#32 Show speech to text data on LiveChat.js
  src/components/atomic/pages/LiveChat.js
Labels: 😸API, 💻Feature, AI
